config/routes.rb
Rails.application.routes.draw do
  # Root page
  root 'home#index'

  # Person
  resources :person

  # Pets
  resources :pet

  # User
  get 'signup'  => 'user#new'
  resources :user

  # Login
  get 'login' => 'session#new'
  delete 'logout' => 'session#destroy'
  resources :session

end

app/models/person.rb
class Person < ActiveRecord::Base
  # File
  has_attached_file :picture,
    default_url: "/images/default.gif"

  # Validations
  validates :name, presence: true
  validates :surname, presence: true
  validates :dni, presence: true, length: {is: 9}, :valid_nif => true, :uniqueness => {:scope => [:name, :surname, :email]}
  validates :email, presence: true
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  # File
  has_attached_file :picture,
    default_url: "/images/default.gif"

  # Validations
  validates :name, presence: true
  validates :age, presence: true
  # validates :alive, presence: true
  validates :sex, presence: true, inclusion: {in: %w(male female), message: "%{value} no es válido"}
  validates :animal_type, presence: true, inclusion: {in: %w(perro gato tortuga conejo), message: "%{value} no es válido"}
  validates :owner, presence: true
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :login, presence: true, :uniqueness => {:scope => [:login, :password_digest]}
  validates :password_digest, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
before_action :authorize, only: [:index, :show, :delete, :create, :edit, :new, :update, :destroy]

def index
  @people = Person.all
end

def new
  @person = Person.new
end

def create
  @person = Person.new(person_params)
  if @person.save
    redirect_to action: 'index'
  else
    render 'new'
  end
  rescue ActiveRecord::RecordNotUnique
    redirect_to action: 'new', error: 'exists'
end

def show
  @person = Person.find(params[:id])
end

def edit
  @person = Person.find(params[:id])
end

def update
  @person = Person.find(params[:id])

  if @person.update(person_params)
    redirect_to action: 'index'
  else
    render 'edit'
  end
end

def destroy
  @person = Person.find(params[:id])
  @person.destroy

  redirect_to action: 'index'
end

private
  def person_params
    params.require(:person).permit(:name, :surname, :dni, :email, :picture, :login)
  end

end

app/controllers/pet_controller.rb
class PetController < ApplicationController
  before_action :authorize, only: [:index, :show, :delete, :create, :edit, :new, :update, :destroy]

def new
  @pet = Pet.new
end

def create
  @pet = Pet.new(pet_params)
  if @pet.save
    redirect_to controller: 'pet', action: 'index', dni: pet_params[:owner]
  else
    render 'new'
  end
end

def show
  @pet = Pet.find(params[:id])
end

def index
  @pets = Pet.where(owner: params[:dni])
end

def edit
  @pet = Pet.find(params[:id])
end

def update
  @pet = Pet.find(params[:id])
  if @pet.update(pet_params)
    redirect_to controller: 'pet', action: 'index', dni: pet_params[:owner]
  else
    render 'edit'
  end
end

def destroy
  @pet = Pet.find(params[:id])
  @pet.destroy
  redirect_to action: 'index', dni: params[:dni]
end

private
  def pet_params
    params.require(:pet).permit(:name, :age, :owner, :alive, :sex, :animal_type, :picture)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_login(user_params[:login])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to '/person'
    else
      redirect_to '/login?error=fail'
    end
  end

 def destroy
   session[:user_id] = nil
   redirect_to '/login'
 end

private
 def user_params
   params.require(:session).permit(:login, :password)
 end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if user_params[:password] != user_params[:password_confirmation]
      rediect_to '/signup'
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/person'
    else
      render '/signup'
    end
  end

private
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/pet_helper.rb
module PetHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="main">
    <h1 class="text-center title">Bienvenido al sistema de control de usuarios</h1>

    <center>
      <button type="button" class="btn btn-outline-success">
        <%= link_to "Gestionar personal", :controller => 'person', :action => 'index'%>
      </button>
    </center>
  </div>
</div>

app/views/layouts/_nav.html.erb
<%= stylesheet_link_tag "nav" %>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand brand"><%= image_tag("company/logo.png") %></a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Inicio", {controller: 'home', action: 'index'}, class: 'nav-link' %>
      </li>
      &nbsp;&nbsp;
      <li class="nav-item">
        <%= link_to "Usuarios", {controller: 'person', action: 'index'}, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if locals[:user] %>
        &nbsp;&nbsp;
        <li class="nav-item">
          ¡Hola, <%=locals[:user].login%>!
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
          <%= link_to "Salir", logout_path, method: "delete" %>
        </li>
      <% else %>
        &nbsp;&nbsp;
        <li class="nav-item">
          <%= link_to "Entrar", 'login' %>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
          <%= link_to "Registrar", 'signup' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'company/logo.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/nav', locals: {user: @current_user} %>
<%= yield %>

</body>
</html>

app/views/person/_form.html.erb
<div>
  <% if @person.errors.any? %>
    <% pluralize(@person.errors.count, "error") %>
      <% @person.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger" role="alert">
        <strong>¡Oh no!</strong> <%= msg %>
      </div>
      <% end %>
    <% end %>
  </div>

  <div class="form">
      <div class="form-group row">
        <%= f.label :name, "Nombre*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control", type: 'text'%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :surname, "Apellidos*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :surname, class: "form-control", type: 'text'%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :email, "Email*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :email, class: "form-control", type: 'email'%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :dni, "DNI*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :dni, class: "form-control", type: 'text', minlength: "9", maxlength: "9"%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :picture, "Imagen: ", class: "col-2 col-form-label" %>
        <div class="col-10">
        <%= f.file_field :picture, class: "form-control-file", accept: ".png, .jpeg, .jpg, .gif" %>
        <small id="fileHelp" class="form-text text-muted">Permited extensions: .png, .jpeg, .jpg, .gif</small>
        </div>
      </div>
      <%= f.hidden_field :login, value: current_user.login %>
      <small>Tags with * symbol are required.</small>
      <center>
      <%= f.submit 'Guardar', class: "btn btn-outline-success" %>
      </center>
  </div>
</div>

app/views/person/edit.html.erb
<div class="container">
  <h1 class="text-center tittle">Editar usuario</h1>
  <%= form_for @person do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>

app/views/person/index.html.erb
<div class="container">
  <h1 class="text-center">Personal</h1>
  <div class=" blocks">
    <% if @people != nil && current_user.login %>
      <% @people.each do |person| %>
        <%if current_user.login == person.login%>
          <div class="card" style="width: 20rem;">
            <center>
              <div class="picture">
                <img class="card-img-top" src=<%=person.picture%> alt="Person image">
              </div>
            </center>
            <div class="card-block">
              <% completeName = person.name + " " + person.surname %>
              <h4 class="card-title text-center"><%= link_to (completeName), person_path(person) %></h4>
            </div>
            <div class="buttonsGroup">
              <button type="button" class="btn btn-outline-warning"><%= link_to (fa_icon "pencil"), edit_person_path(person)%></button>
              <button type="button" class="btn btn-outline-danger"><%= link_to (fa_icon "times"), [person], method: :delete%></button>
              <button type="button" class="btn btn-outline-info"><%= link_to (fa_icon "paw"), controller: 'pet', action: 'index', dni: person.dni %></button>
            </div>
          </div>
        <%end%>
      <% end %>
    <% end %>
  </div>
  <center>
    <button type="button" class="btn btn-outline-primary add"><%= link_to 'Añadir persona', new_person_path %></button>
  </center>
</div>

app/views/person/new.html.erb
<div class="container">
  <h1 class="text-center tittle">Nuevo usuario</h1>
  <%if params[:error] == 'exists'%>
    <div class="alert alert-danger" role="alert">
      <strong>¡Oh no!</strong> El usuario ya existe
    </div>
  <%end%>
  <%= form_for :person, :url => url_for(:controller => 'person', :action => 'create') do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>

app/views/person/show.html.erb
<div class="container main">
  <h1 class="text-center title">Ficha de usuario:</h1>
  <div class="block">
    <div class="image">
      <img src=<%=@person.picture%> alt="Person image" />
    </div>
    <div class="content">
      <ul class="info">
        <li><b>Nombre completo:</b> <%=@person.name%> <%=@person.surname%></li>
        <li><b>Email:</b> <%=@person.email%></li>
        <li><b>DNI:</b> <%=@person.dni%> <%=@person.surname%></li>
      </ul>
    </div>
    <div class="buttonsGroup">
      <button type="button" class="btn btn-outline-warning"><%= link_to (fa_icon "pencil"), edit_person_path(@person)%></button>
      <button type="button" class="btn btn-outline-danger"><%= link_to (fa_icon "times"), [@person], method: :delete%></button>
      <button type="button" class="btn btn-outline-info"><%= link_to (fa_icon "paw"), controller: 'pet', action: 'index', dni: @person.dni %></button>
    </div>
  </div>
</div>

app/views/pet/_form.html.erb
<div class="container">
  <% if @pet.errors.any? %>
    <div>
      <% pluralize(@pet.errors.count, "error") %>
        <% @pet.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
          <strong>¡Oh no!</strong> <%= msg %>
        </div>
        <% end %>
    </div>
  <% end %>

  <div class="form">
      <div class="form-group row">
        <%= f.label :name, "Nombre*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control", type: 'text'%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :age, "Edad*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :age, class: "form-control", type: 'number', min: 0%>
        </div>
      </div>
      <% var_owner = params[:dni] %>
      <div class="form-group row">
        <%= f.label :owner, "Dueño*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :owner, class: "form-control", type: 'text', value: var_owner, readonly: true%>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-2 col-form-label">¿Vive?*:</label>
        <div class="col-10">
          <div class="form-check form-check-inline">
            <%= label :alive, "Sí ", class: "col-2 col-form-label" %>
            <%= f.radio_button :alive, 'true', class: "form-control" %>
          </div>
          <div class="form-check form-check-inline">
            <%= label :alive, "No ", class: "col-2 col-form-label" %>
            <%= f.radio_button :alive, 'false', class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-2 col-form-label">Sexo*:</label>
        <div class="col-10">
          <div class="form-check form-check-inline">
            <%= label :sex, "Hembra ", class: "col-2 col-form-label" %>
            <%= f.radio_button :sex, 'female', class: "form-control"%>
          </div>
          <div class="form-check form-check-inline">
            <%= label :sex, "Macho ", class: "col-2 col-form-label" %>
            <%= f.radio_button :sex, 'male', class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :animal_type, "Tipo*: ", class: "col-2 col-form-label" %>
        <div class="col-10">
            <%= f.select :animal_type, options_for_select([["Selecciona uno", ""], "perro", "gato", "conejo", "tortuga"]),  {}, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :picture, "Imagen: ", class: "col-2 col-form-label" %>
        <div class="col-10">
        <%= f.file_field :picture, class: "form-control-file", accept: ".png, .jpeg, .jpg, .gif" %>
        <small id="fileHelp" class="form-text text-muted">Permited extensions: .png, .jpeg, .jpg, .gif</small>
        </div>
      </div>
      <small>Tags with * symbol are required.</small>
      <center>
      <%= f.submit 'Guardar', class: "btn btn-outline-success add" %>
      </center>
  </div>
</div>

app/views/pet/edit.html.erb
<div class="container">
  <h1 class="text-center">Editar mascota</h1>
  <%= form_for @pet do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>

app/views/pet/index.html.erb
<div class="container">
  <h1 class="text-center">Mis mascotas</h1>
  <div class=" blocks">
    <% if @pets != nil %>
      <% @pets.each do |pet| %>
      <div class="card" style="width: 20rem;">
        <center>
          <div class="picture">
            <img class="card-img-top" src=<%=pet.picture%> alt="Pet image">
          </div>
        </center>
        <div class="card-block">
          <h4 class="card-title text-center"><%= link_to (pet.name), pet_path(pet) %></h4>
        </div>
        <div class="buttonsGroup">
          <button type="button" class="btn btn-outline-warning"><%= link_to (fa_icon "pencil"), edit_pet_path(pet, dni: params[:dni])%></button>
          <button type="button" class="btn btn-outline-danger"><%= link_to (fa_icon "times"), pet_path(pet, dni: params[:dni]), method: :delete%></button>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
  <center>
    <button type="button" class="btn btn-outline-primary add"><%= link_to 'Añadir mascota', new_pet_path(dni: params[:dni]) %></button>
  </center>
</div>

app/views/pet/new.html.erb
<div class="container">
  <h1 class="text-center">Nueva mascota</h1>
  <%= form_for :pet, :url => url_for(:controller => 'pet', :action => 'create') do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>

app/views/pet/show.html.erb
<div class="container main">
  <h1 class="text-center title">Ficha de la mascota:</h1>
  <div class="block">
    <div class="image">
      <img src=<%=@pet.picture%> alt="Pet image" />
    </div>
    <div class="content">
      <ul class="info">
        <li><b>Nombre: </b> <%=@pet.name%></li>
        <li><b>Edad: </b> <%=@pet.age%> años</li>
        <% if @pet.sex == 'female' %>
            <li><b>Sexo: </b>hembra</li>
        <% else %>
            <li><b>Sexo: </b>macho</li>
        <% end %>
        <li><b>Tipo: </b> <%=@pet.animal_type%></li>
        <% if @pet.alive == true %>
            <li><b>¿Está vivo? </b>Sí</li>
        <% else %>
            <li><b>¿Está vivo? </b>No</li>
        <% end %>
      </ul>
    </div>
    <div class="buttonsGroup">
      <button type="button" class="btn btn-outline-warning"><%= link_to (fa_icon "pencil"), edit_pet_path(@pet, dni: @pet.owner)%></button>
      <button type="button" class="btn btn-outline-danger"><%= link_to (fa_icon "times"), pet_path(@pet, dni: @pet.owner), method: :delete%></button>
    </div>
  </div>
</div>

app/views/session/_form.html.erb
<div class="container">
  <%if params[:error]%>
    <div class="alert alert-danger" role="alert">
      Hay un error con tus datos
    </div>
  <%end%>
  <div class="form">
    <div class="form-group row">
      <%= f.label :login, "Usuario: ", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :login, class: "form-control", type: 'text'%>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :password, "Contraseña: ", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :password, class: "form-control", type: 'password'%>
      </div>
    </div>
    <center>
    <%= f.submit 'Entrar', class: "btn btn-outline-success add" %>
    </center>
  </div>
</div>

app/views/session/new.html.erb
<div class="container">
  <h1 class="text-center">Accede o <%= link_to 'regístrate', controller: 'user', action: 'new' %></h1>
  <%= form_for :session, :url => url_for(:controller => 'session', :action => 'create') do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>

app/views/user/_form.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <div>
      <% pluralize(@user.errors.count, "error") %>
        <% @user.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
          <strong>Oh no!</strong> <%= msg %>
        </div>
        <% end %>
    </div>
  <% end %>

  <div class="form">
    <div class="form-group row">
      <%= f.label :login, "Usuario: ", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :login, class: "form-control", type: 'text'%>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :password, "Contraseña: ", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :password, class: "form-control", type: 'password'%>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :password_confirmation, "Repite la contraseña: ", class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :password_confirmation, class: "form-control", type: 'password'%>
      </div>
    </div>
    <center>
    <%= f.submit 'Registrar', class: "btn btn-outline-success add" %>
    </center>
  </div>
</div>

app/views/user/new.html.erb
<div class="container">
  <h1 class="text-center">Registrate o <%= link_to 'accede', controller: 'session', action: 'new' %></h1>
  <%= form_for :user, :url => url_for(:controller => 'user', :action => 'create') do |f| %>
    <%=render 'form', f: f%>
  <%end%>
</div>